
version: '3.8'

networks:
  integration-test-example:

services:
  it_test:
    image: amazoncorretto:17.0.9-alpine3.18
    volumes:
      - .:/demo
    working_dir: /demo
    depends_on:
      - db
    networks:
      - integration-test-example
    command: [ "./gradlew","clean","integrationTest" ]
  db:
    image: postgres:16.0
    environment:
      POSTGRES_DB: lotto
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    restart: on-failure
    volumes:
      # - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
