version: '3.8'

services:
  app:
    build: .
    ports:
      - "8888:8888"
    networks:
      - lotto-net
    environment:
      - DATABASE_URL=jdbc:postgresql://postgres:5432/lotto
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: lotto
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    restart: on-failure
    volumes:
      # - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    networks:
      - lotto-net
networks:
  lotto-net:
volumes:
  pgdata:
